In [1]:
"""
Write a function so that the columns of the output matrix are powers of the input  vector.  
The order of the powers is determined by the increasing boolean argument. 
Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.   
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.  
"""
import numpy as np
import numpy.matlib

array=np.array([0,1,2,3,4])


largearray=np.array([])
for i in range(0,len(array)):
    smallarray=np.array([])
    for j in range(0,len(array)):
        smallarray=np.append(smallarray,array[j]**i)
        #print(smallarray,array[j]**i)
    #print(smallarray)
    largearray=np.append(largearray,smallarray)

matrix=numpy.matlib.array(largearray).reshape(len(smallarray),len(smallarray)).T
print(matrix)


[[  1.   0.   0.   0.   0.]
 [  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]


In [2]:
"""
Problem Statement 2:  
Given a sequence of n values x1, x2, ..., xn and a window size k>0, 
the k-th moving average of the given sequence is defined as follows:  
The moving average sequence has n-k+1 elements as shown below.  
The moving averages with k=4 of a ten-value sequence (n=10) is shown below  
i 1  2  3  4  5  6  7  8  9 10  ===== == == == == == == == == == ==  I
nput 10 20 30 40 50 60 70 80 90 100 
y1      25 = (10+20+30+40)/4 
y2      35 = (20+30+40+50)/4 
y3      45 = (30+40+50+60)/4  
y4      55 = (40+50+60+70)/4
y5      65 = (50+60+70+80)/4 
y6      75 = (60+70+80+90)/4
y7      85 = (70+80+90+100)/4   
Thus, the moving average sequence has n-k+1=10-4+1=7 values. 
Question: Write a function to find moving average in an array over a window:          
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 
"""

import numpy as np
array=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window=4
k=len(array)-window+1
inc=1
start=0

while(1==1):
    end=start+window
    sum1=0
    if(start==k):
        break
    for i in range(start,end):
        sum1=sum1+array[i]
        #print(array[i],end=" ")
    print("y",inc,sep="",end="  =  ")
    print(sum1/window)
    start=start+1
    inc=inc+1
    #print("\n")
        


y1  =  4.25
y2  =  5.5
y3  =  6.75
y4  =  7.75
y5  =  23.5
y6  =  39.5
y7  =  57.25
y8  =  79.25
y9  =  88.0
y10  =  107.5
